version: '3.8'

services:
  express-app:
    container_name: asbi-api
    build: .
    ports:
      - "4001:4001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
networks:
  web:
    external: true
